SystemOrganization addCategory: #'Phanide-SyntaxHighlighting'!
SystemOrganization addCategory: 'Phanide-SyntaxHighlighting-Commands'!
SystemOrganization addCategory: 'Phanide-SyntaxHighlighting-Regex'!
SystemOrganization addCategory: 'Phanide-SyntaxHighlighting-Rubric'!
SystemOrganization addCategory: 'Phanide-SyntaxHighlighting-Style'!
SystemOrganization addCategory: 'Phanide-SyntaxHighlighting-Styler'!
SystemOrganization addCategory: 'Phanide-SyntaxHighlighting-Tests'!
