"
I represent an hex editor.
"
Class {
	#name : #PhanideBrowserHexEditor,
	#superclass : #PhanideBrowserFileEditor,
	#category : 'Phanide-Browser-UI'
}

{ #category : #specs }
PhanideBrowserHexEditor class >> defaultSpec [
	^ self specLayout
]

{ #category : #'as yet unclassified' }
PhanideBrowserHexEditor >> fileChanged [
]

{ #category : #initialization }
PhanideBrowserHexEditor >> initializeWidgets [
]
