"
I am event handler for events fired by gdb.
"
Class {
	#name : #PhanideGDBEventHandler,
	#superclass : #Object,
	#category : 'Phanide-GDB-FrontEnd'
}

{ #category : #'as yet unclassified' }
PhanideGDBEventHandler >> onConsoleOutput: aString [
]

{ #category : #'as yet unclassified' }
PhanideGDBEventHandler >> onLogOutput: aString [
]

{ #category : #'as yet unclassified' }
PhanideGDBEventHandler >> onTargetOutput: aString [
]
